version: "3"
services:
  node-app:
    container_name: newapp
    image: hamzaesmael/new-app-of-docker
    build: .
    ports:
      - "4000:4000"
    env_file:
      - ./.env
    depends_on:
      - redis
  redis:
    image: redis
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - node-app
    

    

